### ISSUE TITLE
fhem path correct in DockerFile?

### ISSUE THREAD

**Issue by SpaceTeddy** [KastB/addon-fhem#5]
check this out:

`RUN rm -rf /opt/fehm && chmod a+x /run.sh`

**Comment by KastB** [comment]
What's wrong with this?
It's quite some time I did this, but my guess would be, that there had been issues with the permissions of this folder and that's why it will be created, bind-mounted and used by the run.sh
Whats the issue you are observing?

**Comment by SpaceTeddy** [comment]
Well, I thought that there is a typo somewhere in the fhem path. -> /opt/fehm
But could also ok, I‘m not an docker expert.

cu chris

**Comment by KastB** [comment]
Oh dear - sorry.
I haven't noticed it even on the second read.
Thank you for pointing it out. I hope it is fixed now.
Cheers

**Comment by rubinho76** [comment]
Hi Guys,
something is still wrong.
I can no longer install the current version :(

![grafik](https://github.com/KastB/addon-fhem/assets/8414325/77df6213-0151-4f59-a19c-c6558c1da8eb)

**Comment by rubinho76** [comment]
With version 0.0.9 the problem is fixed.
Thanks
